### ISSUE TITLE
Usability issues with buttons

### ISSUE THREAD

**Issue by luminarious** [antfu/foto-rehearse#2]
Hey, if I may point out two issues with the icon buttons:

- No idea what they do, a tooltip would help (at least [title attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title))
- Use <[button type="button"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)> if you care about html at all 😅

**Comment by antfu** [comment]
I didn't know you can have a tooltip with the title attr XD. I will make adjustments then thank you!

**Comment by antfu** [comment]
Fixed. Let me know if there is anything I can do. Thanks!

**Comment by luminarious** [comment]
Much better, thank you!
